server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:9090/OTM?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: false
    open-in-view: false



